sudo: required
services:
- docker
language: go
script:
# build image
- docker build -t andrevs/git-sync .
# test image
# - docker run spanghf37/knxd uname -a
## push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker tag andrevs/git-sync andrevs/git-sync:latest
- docker push andrevs/git-sync:latest
